site_name: browser-mcp
site_description: Browser MCP server documentation
site_url: https://github.com/kietle/browser-mcp
repo_url: https://github.com/kietle/browser-mcp
theme:
  name: material
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Release process: release.md
  - Changelog: changelog.md
